//! The document-level charge reason code
//! (`BT-105`/`BT-145`, subset of `UNCL7161`).
//!
//! Source: [EN-16931 codelist](https://github.com/ConnectingEurope/eInvoicing-EN16931/blob/master/ubl/schematron/codelist/EN16931-UBL-codes.sch), rule `BR-CL-20`.

use crate::Error;
use crate::prelude::*;

/// The charge reason (`UNCL7161`): why a charge is applied.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Display, FromStr)]
pub enum ChargeReason {
    #[display("AA")]
    Advertising,
    #[display("AAA")]
    Telecommunication,
    #[display("AAC")]
    TechnicalModification,
    #[display("AAD")]
    JobOrderProduction,
    #[display("AAE")]
    Outlays,
    #[display("AAF")]
    OffPremises,
    #[display("AAH")]
    AdditionalProcessing,
    #[display("AAI")]
    Attesting,
    #[display("AAS")]
    Acceptance,
    #[display("AAT")]
    RushDelivery,
    #[display("AAV")]
    SpecialConstruction,
    #[display("AAY")]
    AirportFacilities,
    #[display("AAZ")]
    Concession,
    #[display("ABA")]
    CompulsoryStorage,
    #[display("ABB")]
    FuelRemoval,
    #[display("ABC")]
    IntoPlane,
    #[display("ABD")]
    Overtime,
    #[display("ABF")]
    Tooling,
    #[display("ABK")]
    Miscellaneous,
    #[display("ABL")]
    AdditionalPackaging,
    #[display("ABN")]
    Dunnage,
    #[display("ABR")]
    Containerisation,
    #[display("ABS")]
    CartonPacking,
    #[display("ABT")]
    HessianWrapped,
    #[display("ABU")]
    PolyethyleneWrapPacking,
    #[display("ACF")]
    MiscellaneousTreatment,
    #[display("ACG")]
    EnamellingTreatment,
    #[display("ACH")]
    HeatTreatment,
    #[display("ACI")]
    PlatingTreatment,
    #[display("ACJ")]
    Painting,
    #[display("ACK")]
    Polishing,
    #[display("ACL")]
    Priming,
    #[display("ACM")]
    PreservationTreatment,
    #[display("ACS")]
    Fitting,
    #[display("ADC")]
    Consolidation,
    #[display("ADE")]
    BillOfLading,
    #[display("ADJ")]
    Airbag,
    #[display("ADK")]
    Transfer,
    #[display("ADL")]
    Slipsheet,
    #[display("ADM")]
    Binding,
    #[display("ADN")]
    RepairOrReplacementOfBrokenReturnablePackage,
    #[display("ADO")]
    EfficientLogistics,
    #[display("ADP")]
    Merchandising,
    #[display("ADQ")]
    ProductMix,
    #[display("ADR")]
    OtherServices,
    #[display("ADT")]
    PickUp,
    #[display("ADW")]
    ChronicIllness,
    #[display("ADY")]
    NewProductIntroduction,
    #[display("ADZ")]
    DirectDelivery,
    #[display("AEA")]
    Diversion,
    #[display("AEB")]
    Disconnect,
    #[display("AEC")]
    Distribution,
    #[display("AED")]
    HandlingOfHazardousCargo,
    #[display("AEF")]
    RentsAndLeases,
    #[display("AEH")]
    LocationDifferential,
    #[display("AEI")]
    AircraftRefueling,
    #[display("AEJ")]
    FuelShippedIntoStorage,
    #[display("AEK")]
    CashOnDelivery,
    #[display("AEL")]
    SmallOrderProcessingService,
    #[display("AEM")]
    ClericalOrAdministrativeServices,
    #[display("AEN")]
    Guarantee,
    #[display("AEO")]
    CollectionAndRecycling,
    #[display("AEP")]
    CopyrightFeeCollection,
    #[display("AES")]
    VeterinaryInspectionService,
    #[display("AET")]
    PensionerService,
    #[display("AEU")]
    MedicineFreePassHolder,
    #[display("AEV")]
    EnvironmentalProtectionService,
    #[display("AEW")]
    EnvironmentalCleanUpService,
    #[display("AEX")]
    NationalChequeProcessingServiceOutsideAccountArea,
    #[display("AEY")]
    NationalPaymentServiceOutsideAccountArea,
    #[display("AEZ")]
    NationalPaymentServiceWithinAccountArea,
    #[display("AJ")]
    Adjustments,
    #[display("AU")]
    Authentication,
    #[display("CA")]
    Cataloguing,
    #[display("CAB")]
    Cartage,
    #[display("CAD")]
    Certification,
    #[display("CAE")]
    CertificateOfConformance,
    #[display("CAF")]
    CertificateOfOrigin,
    #[display("CAI")]
    Cutting,
    #[display("CAJ")]
    ConsularService,
    #[display("CAK")]
    CustomerCollection,
    #[display("CAL")]
    PayrollPaymentService,
    #[display("CAM")]
    CashTransportation,
    #[display("CAN")]
    HomeBankingService,
    #[display("CAO")]
    BilateralAgreementService,
    #[display("CAP")]
    InsuranceBrokerageService,
    #[display("CAQ")]
    ChequeGeneration,
    #[display("CAR")]
    PreferentialMerchandisingLocation,
    #[display("CAS")]
    Crane,
    #[display("CAT")]
    SpecialColourService,
    #[display("CAU")]
    Sorting,
    #[display("CAV")]
    BatteryCollectionAndRecycling,
    #[display("CAW")]
    ProductTakeBackFee,
    #[display("CAX")]
    QualityControlReleased,
    #[display("CAY")]
    QualityControlHeld,
    #[display("CAZ")]
    QualityControlEmbargo,
    #[display("CD")]
    CarLoading,
    #[display("CG")]
    Cleaning,
    #[display("CS")]
    CigaretteStamping,
    #[display("CT")]
    CountAndRecount,
    #[display("DAB")]
    LayoutDesign,
    #[display("DAC")]
    AssortmentAllowance,
    #[display("DAD")]
    DriverAssignedUnloading,
    #[display("DAF")]
    DebtorBound,
    #[display("DAG")]
    DealerAllowance,
    #[display("DAH")]
    AllowanceTransferableToTheConsumer,
    #[display("DAI")]
    GrowthOfBusiness,
    #[display("DAJ")]
    IntroductionAllowance,
    #[display("DAK")]
    MultiBuyPromotion,
    #[display("DAL")]
    Partnership,
    #[display("DAM")]
    ReturnHandling,
    #[display("DAN")]
    MinimumOrderNotFulfilledCharge,
    #[display("DAO")]
    PointOfSalesThresholdAllowance,
    #[display("DAP")]
    WholesalingDiscount,
    #[display("DAQ")]
    DocumentaryCreditsTransferCommission,
    #[display("DL")]
    Delivery,
    #[display("EG")]
    Engraving,
    #[display("EP")]
    Expediting,
    #[display("ER")]
    ExchangeRateGuarantee,
    #[display("FAA")]
    Fabrication,
    #[display("FAB")]
    FreightEqualization,
    #[display("FAC")]
    FreightExtraordinaryHandling,
    #[display("FC")]
    FreightService,
    #[display("FH")]
    FillingHandling,
    #[display("FI")]
    Financing,
    #[display("GAA")]
    Grinding,
    #[display("HAA")]
    Hose,
    #[display("HD")]
    Handling,
    #[display("HH")]
    HoistingAndHauling,
    #[display("IAA")]
    Installation,
    #[display("IAB")]
    InstallationAndWarranty,
    #[display("ID")]
    InsideDelivery,
    #[display("IF")]
    Inspection,
    #[display("IR")]
    InstallationAndTraining,
    #[display("IS")]
    Invoicing,
    #[display("KO")]
    Koshering,
    #[display("L1")]
    CarrierCount,
    #[display("LA")]
    Labelling,
    #[display("LAA")]
    Labour,
    #[display("LAB")]
    RepairAndReturn,
    #[display("LF")]
    Legalisation,
    #[display("MAE")]
    Mounting,
    #[display("MI")]
    MailInvoice,
    #[display("ML")]
    MailInvoiceToEachLocation,
    #[display("NAA")]
    NonReturnableContainers,
    #[display("OA")]
    OutsideCableConnectors,
    #[display("PA")]
    InvoiceWithShipment,
    #[display("PAA")]
    Phosphatizing,
    #[display("PC")]
    Packing,
    #[display("PL")]
    Palletizing,
    #[display("PRV")]
    PriceVariation,
    #[display("RAB")]
    Repacking,
    #[display("RAC")]
    Repair,
    #[display("RAD")]
    ReturnableContainer,
    #[display("RAF")]
    Restocking,
    #[display("RE")]
    ReDelivery,
    #[display("RF")]
    Refurbishing,
    #[display("RH")]
    RailWagonHire,
    #[display("RV")]
    Loading,
    #[display("SA")]
    Salvaging,
    #[display("SAA")]
    ShippingAndHandling,
    #[display("SAD")]
    SpecialPackaging,
    #[display("SAE")]
    Stamping,
    #[display("SAI")]
    ConsigneeUnload,
    #[display("SG")]
    ShrinkWrap,
    #[display("SH")]
    SpecialHandling,
    #[display("SM")]
    SpecialFinish,
    #[display("SU")]
    SetUp,
    #[display("TAB")]
    TankRenting,
    #[display("TAC")]
    Testing,
    #[display("TT")]
    TransportationThirdPartyBilling,
    #[display("TV")]
    TransportationByVendor,
    #[display("V1")]
    DropYard,
    #[display("V2")]
    DropDock,
    #[display("WH")]
    Warehousing,
    #[display("XAA")]
    CombineAllSameDayShipment,
    #[display("YY")]
    SplitPickUp,
    #[display("ZZZ")]
    MutuallyDefined,
}

impl TryFrom<&str> for ChargeReason {
    type Error = Error;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        <Self as FromStr>::from_str(value).map_err(Into::into)
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn parses_a_known_code() {
        let reason: ChargeReason = "AA".parse().expect("AA is a valid charge reason");

        assert_eq!(reason, ChargeReason::Advertising);
        assert_eq!(reason.to_string(), "AA");
    }

    #[test]
    fn rejects_an_unknown_code() {
        assert!("XYZ".parse::<ChargeReason>().is_err());
    }

    #[test]
    fn converts_via_try_from() {
        assert_eq!(
            ChargeReason::try_from("AEN").expect("AEN is a valid charge reason"),
            ChargeReason::Guarantee
        );
        assert!(matches!(
            ChargeReason::try_from("XYZ"),
            Err(Error::InvalidValue { .. })
        ));
    }
}
