//! The invoiced object identifier scheme code (`BT-18`, UNTDID 1153).
//!
//! Source: [EN-16931 codelist](https://github.com/ConnectingEurope/eInvoicing-EN16931/blob/master/ubl/schematron/codelist/EN16931-UBL-codes.sch), rule `BR-CL-07`.
//! Variant names follow [UNTDID 1153](https://service.unece.org/trade/untdid/d23a/tred/tred1153.htm).

use crate::Error;
use crate::prelude::*;

/// The invoiced object identifier scheme (`BT-18`, UNTDID 1153): the qualifier of an
/// identifier for an object the invoice refers to (a contract, subscription, meter, and so on).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Display, FromStr)]
pub enum InvoicedObjectType {
    #[display("AAA")]
    OrderAcknowledgement,
    #[display("AAB")]
    ProformaInvoice,
    #[display("AAC")]
    DocumentaryCredit,
    #[display("AAD")]
    ContractAddendum,
    #[display("AAE")]
    GoodsDeclaration,
    #[display("AAF")]
    DebitCard,
    #[display("AAG")]
    Offer,
    #[display("AAH")]
    BankBatchInterbankTransaction,
    #[display("AAI")]
    BankIndividualInterbankTransaction,
    #[display("AAJ")]
    DeliveryOrder,
    #[display("AAK")]
    DespatchAdvice,
    #[display("AAL")]
    Drawing,
    #[display("AAM")]
    Waybill,
    #[display("AAN")]
    DeliverySchedule,
    #[display("AAO")]
    ConsignmentConsigneeAssigned,
    #[display("AAP")]
    PartialShipment,
    #[display("AAQ")]
    TransportEquipment,
    #[display("AAR")]
    MunicipalityAssignedBusinessRegistry,
    #[display("AAS")]
    TransportContract,
    #[display("AAT")]
    MasterLabel,
    #[display("AAU")]
    DespatchNote,
    #[display("AAV")]
    Enquiry,
    #[display("AAW")]
    Docket,
    #[display("AAX")]
    CivilAction,
    #[display("AAY")]
    CarrierAgent,
    #[display("AAZ")]
    Scac,
    #[display("ABA")]
    CustomsValuationDecision,
    #[display("ABB")]
    EndUseAuthorization,
    #[display("ABC")]
    AntiDumpingCase,
    #[display("ABD")]
    CustomsTariff,
    #[display("ABE")]
    Declarant,
    #[display("ABF")]
    RepairEstimate,
    #[display("ABG")]
    CustomsDecisionRequest,
    #[display("ABH")]
    SubHouseBillOf,
    #[display("ABI")]
    TaxPayment,
    #[display("ABJ")]
    Quota,
    #[display("ABK")]
    TransitGuarantee,
    #[display("ABL")]
    CustomsGuarantee,
    #[display("ABM")]
    ReplacingPart,
    #[display("ABN")]
    SellerCatalogue,
    #[display("ABO")]
    Originator,
    #[display("ABP")]
    DeclarantCustomsIdentity,
    #[display("ABQ")]
    Importer,
    #[display("ABR")]
    ExportClearanceInstruction,
    #[display("ABS")]
    ImportClearanceInstruction,
    #[display("ABT")]
    GoodsDeclarationCustoms,
    #[display("ABU")]
    Article,
    #[display("ABV")]
    IntraPlantRouting,
    #[display("ABW")]
    StockKeepingUnit,
    #[display("ABX")]
    TextElementDeletion,
    #[display("ABY")]
    Allotment,
    #[display("ABZ")]
    VehicleLicence,
    #[display("AC")]
    AirCargoTransferManifest,
    #[display("ACA")]
    CargoAcceptanceOrder,
    #[display("ACB")]
    UsGovernmentAgency,
    #[display("ACC")]
    ShippingUnit,
    #[display("ACD")]
    Additional,
    #[display("ACE")]
    Related,
    #[display("ACF")]
    Addressee,
    #[display("ACG")]
    ATACarnet,
    #[display("ACH")]
    PackagingUnit,
    #[display("ACI")]
    OuterpackagingUnit,
    #[display("ACJ")]
    CustomerMaterialSpecification,
    #[display("ACK")]
    Bank,
    #[display("ACL")]
    Principal,
    #[display("ACN")]
    CollectionAdvice,
    #[display("ACO")]
    IronCharge,
    #[display("ACP")]
    HotRoll,
    #[display("ACQ")]
    ColdRoll,
    #[display("ACR")]
    RailwayWagon,
    #[display("ACT")]
    UniqueClaimsOfThe,
    #[display("ACU")]
    LossEvent,
    #[display("ACV")]
    EstimateOrder,
    #[display("ACW")]
    PreviousMessage,
    #[display("ACX")]
    BankerAcceptance,
    #[display("ACY")]
    DutyMemo,
    #[display("ACZ")]
    EquipmentTransportCharge,
    #[display("ADA")]
    BuyerItem,
    #[display("ADB")]
    MaturedCertificateOfDeposit,
    #[display("ADC")]
    Loan,
    #[display("ADD")]
    AnalysisTest,
    #[display("ADE")]
    Account,
    #[display("ADF")]
    Treaty,
    #[display("ADG")]
    Catastrophe,
    #[display("ADI")]
    BureauSigning,
    #[display("ADJ")]
    CompanySyndicate,
    #[display("ADK")]
    CompanySyndicateADK,
    #[display("ADL")]
    OrderingCustomerConsignment,
    #[display("ADM")]
    ShipownerAuthorization,
    #[display("ADN")]
    InlandTransportOrder,
    #[display("ADO")]
    ContainerWorkOrder,
    #[display("ADP")]
    Statement,
    #[display("ADQ")]
    UniqueMarket,
    #[display("ADT")]
    GroupAccounting,
    #[display("ADU")]
    Broker,
    #[display("ADV")]
    BrokerADV,
    #[display("ADW")]
    LloydClaimsOffice,
    #[display("ADX")]
    SecureDeliveryTermsAnd,
    #[display("ADY")]
    Report,
    #[display("ADZ")]
    TraderAccount,
    #[display("AE")]
    AuthorizationForExpense,
    #[display("AEA")]
    GovernmentAgency,
    #[display("AEB")]
    Assembly,
    #[display("AEC")]
    Symbol,
    #[display("AED")]
    Commodity,
    #[display("AEE")]
    EurCertificate,
    #[display("AEF")]
    CustomerProcessSpecification,
    #[display("AEG")]
    CustomerSpecification,
    #[display("AEH")]
    ApplicableInstructionsOrStandards,
    #[display("AEI")]
    RegistrationOfPreviousCustoms,
    #[display("AEJ")]
    PostEntry,
    #[display("AEK")]
    PaymentOrder,
    #[display("AEL")]
    Delivery,
    #[display("AEM")]
    TransportRoute,
    #[display("AEN")]
    CustomerUnitInventory,
    #[display("AEO")]
    ProductReservation,
    #[display("AEP")]
    Project,
    #[display("AEQ")]
    DrawingList,
    #[display("AER")]
    ProjectSpecification,
    #[display("AES")]
    Primary,
    #[display("AET")]
    RequestForCancellation,
    #[display("AEU")]
    SupplierControl,
    #[display("AEV")]
    ShippingNote,
    #[display("AEW")]
    EmptyContainerBill,
    #[display("AEX")]
    NonNegotiableMaritimeTransport,
    #[display("AEY")]
    SubstituteAirWaybill,
    #[display("AEZ")]
    DespatchNoteAEZ,
    #[display("AF")]
    AirlinesFlight,
    #[display("AFA")]
    ThroughBillOfLading,
    #[display("AFB")]
    CargoManifest,
    #[display("AFC")]
    Bordereau,
    #[display("AFD")]
    CustomsItem,
    #[display("AFE")]
    ExportControlCommodity,
    #[display("AFF")]
    MarkingLabel,
    #[display("AFG")]
    Tariff,
    #[display("AFH")]
    ReplenishmentPurchaseOrder,
    #[display("AFI")]
    ImmediateTransportationForIn,
    #[display("AFJ")]
    TransportationExportationForIn,
    #[display("AFK")]
    ImmediateExportationForIn,
    #[display("AFL")]
    AssociatedInvoices,
    #[display("AFM")]
    SecondaryCustoms,
    #[display("AFN")]
    AccountParty,
    #[display("AFO")]
    Beneficiary,
    #[display("AFP")]
    SecondBeneficiary,
    #[display("AFQ")]
    ApplicantBank,
    #[display("AFR")]
    IssuingBank,
    #[display("AFS")]
    BeneficiaryBank,
    #[display("AFT")]
    DirectPaymentValuation,
    #[display("AFU")]
    DirectPaymentValuationRequest,
    #[display("AFV")]
    QuantityValuation,
    #[display("AFW")]
    QuantityValuationRequest,
    #[display("AFX")]
    BillOfQuantities,
    #[display("AFY")]
    PaymentValuation,
    #[display("AFZ")]
    Situation,
    #[display("AGA")]
    AgreementToPay,
    #[display("AGB")]
    ContractParty,
    #[display("AGC")]
    AccountPartyBank,
    #[display("AGD")]
    AgentBank,
    #[display("AGE")]
    Agent,
    #[display("AGF")]
    Applicant,
    #[display("AGG")]
    Dispute,
    #[display("AGH")]
    CreditRatingAgency,
    #[display("AGI")]
    Request,
    #[display("AGJ")]
    SingleTransactionSequence,
    #[display("AGK")]
    Application,
    #[display("AGL")]
    DeliveryVerificationCertificate,
    #[display("AGM")]
    TemporaryImportation,
    #[display("AGN")]
    QuotedOnStatement,
    #[display("AGO")]
    SenderToTheOriginal,
    #[display("AGP")]
    CompanyIssuedEquipment,
    #[display("AGQ")]
    DomesticFlight,
    #[display("AGR")]
    InternationalFlight,
    #[display("AGS")]
    EmployerOfServiceBureau,
    #[display("AGT")]
    ServiceGroup,
    #[display("AGU")]
    Member,
    #[display("AGV")]
    PreviousMember,
    #[display("AGW")]
    SchemePlan,
    #[display("AGX")]
    PreviousSchemePlan,
    #[display("AGY")]
    ReceivingPartyMember,
    #[display("AGZ")]
    Payroll,
    #[display("AHA")]
    PackagingSpecification,
    #[display("AHB")]
    AuthorityIssuedEquipment,
    #[display("AHC")]
    TrainingFlight,
    #[display("AHD")]
    Fund,
    #[display("AHE")]
    Signal,
    #[display("AHF")]
    MajorForceProgram,
    #[display("AHG")]
    Nomination,
    #[display("AHH")]
    LaboratoryRegistration,
    #[display("AHI")]
    TransportContractAHI,
    #[display("AHJ")]
    Payee,
    #[display("AHK")]
    Payer,
    #[display("AHL")]
    Creditor,
    #[display("AHM")]
    Debtor,
    #[display("AHN")]
    JointVenture,
    #[display("AHO")]
    ChamberOfCommerceRegistration,
    #[display("AHP")]
    TaxRegistration,
    #[display("AHQ")]
    Wool,
    #[display("AHR")]
    WoolTax,
    #[display("AHS")]
    MeatProcessingEstablishmentRegistration,
    #[display("AHT")]
    QuarantineTreatmentStatus,
    #[display("AHU")]
    RequestForQuote,
    #[display("AHV")]
    ManualProcessingAuthority,
    #[display("AHX")]
    RateNote,
    #[display("AHY")]
    FreightForwarder,
    #[display("AHZ")]
    CustomsRelease,
    #[display("AIA")]
    Compliance,
    #[display("AIB")]
    DepartmentOfTransportationBond,
    #[display("AIC")]
    ExportEstablishment,
    #[display("AID")]
    CertificateOfConformity,
    #[display("AIE")]
    MinisterialCertificateOfHomologation,
    #[display("AIF")]
    PreviousDeliveryInstruction,
    #[display("AIG")]
    Passport,
    #[display("AIH")]
    CommonTransaction,
    #[display("AII")]
    BankCommonTransaction,
    #[display("AIJ")]
    CustomerIndividualTransaction,
    #[display("AIK")]
    BankIndividualTransaction,
    #[display("AIL")]
    CustomerCommonTransaction,
    #[display("AIM")]
    IndividualTransaction,
    #[display("AIN")]
    ProductSourcingAgreement,
    #[display("AIO")]
    CustomsTranshipment,
    #[display("AIP")]
    CustomsPreferenceInquiry,
    #[display("AIQ")]
    PackingPlant,
    #[display("AIR")]
    OriginalCertificate,
    #[display("AIS")]
    ProcessingPlant,
    #[display("AIT")]
    SlaughterPlant,
    #[display("AIU")]
    ChargeCardAccount,
    #[display("AIV")]
    Event,
    #[display("AIW")]
    TransportSection,
    #[display("AIX")]
    ReferredProductForMechanical,
    #[display("AIY")]
    ReferredProductForChemical,
    #[display("AIZ")]
    ConsolidatedInvoice,
    #[display("AJA")]
    PartIndicatorInDrawing,
    #[display("AJB")]
    UsCodeOfFederalRegulations,
    #[display("AJC")]
    PurchasingActivityClause,
    #[display("AJD")]
    UsDefenseFederalAcquisition,
    #[display("AJE")]
    AgencyClause,
    #[display("AJF")]
    CircularPublication,
    #[display("AJG")]
    UsFederalAcquisition,
    #[display("AJH")]
    UsGeneralServicesAdministration,
    #[display("AJI")]
    UsFederalInformationResources,
    #[display("AJJ")]
    Paragraph,
    #[display("AJK")]
    SpecialInstructions,
    #[display("AJL")]
    SiteSpecificProceduresTerms,
    #[display("AJM")]
    MasterSolicitationProceduresTerms,
    #[display("AJN")]
    UsVeteransAffairsAcquisition,
    #[display("AJO")]
    MilitaryInterdepartmentalPurchaseRequest,
    #[display("AJP")]
    ForeignMilitarySales,
    #[display("AJQ")]
    DefensePrioritiesAllocationSystem,
    #[display("AJR")]
    WageDetermination,
    #[display("AJS")]
    Agreement,
    #[display("AJT")]
    Sic,
    #[display("AJU")]
    EndItem,
    #[display("AJV")]
    FederalSupplyScheduleItem,
    #[display("AJW")]
    Technical,
    #[display("AJX")]
    TechnicalOrder,
    #[display("AJY")]
    Suffix,
    #[display("AJZ")]
    TransportationAccount,
    #[display("AKA")]
    ContainerDispositionOrder,
    #[display("AKB")]
    ContainerPrefix,
    #[display("AKC")]
    TransportEquipmentReturn,
    #[display("AKD")]
    TransportEquipmentSurvey,
    #[display("AKE")]
    TransportEquipmentSurveyReport,
    #[display("AKF")]
    TransportEquipmentStuffingOrder,
    #[display("AKG")]
    Vehicle,
    #[display("AKH")]
    GovernmentBillOfLading,
    #[display("AKI")]
    OrderingCustomerSecond,
    #[display("AKJ")]
    DirectDebit,
    #[display("AKK")]
    MeterReadingAtThe,
    #[display("AKL")]
    MeterReadingEnd,
    #[display("AKM")]
    ReplenishmentPurchaseOrderRange,
    #[display("AKN")]
    ThirdBank,
    #[display("AKO")]
    ActionAuthorization,
    #[display("AKP")]
    Appropriation,
    #[display("AKQ")]
    ProductChangeAuthority,
    #[display("AKR")]
    GeneralCargoConsignment,
    #[display("AKS")]
    CatalogueSequence,
    #[display("AKT")]
    ForwardingOrder,
    #[display("AKU")]
    TransportEquipmentSurveyAKU,
    #[display("AKV")]
    LeaseContract,
    #[display("AKW")]
    TransportCosts,
    #[display("AKX")]
    TransportEquipmentStrippingOrder,
    #[display("AKY")]
    PriorPolicy,
    #[display("AKZ")]
    Policy,
    #[display("ALA")]
    ProcurementBudget,
    #[display("ALB")]
    DomesticInventoryManagement,
    #[display("ALC")]
    CustomerAssignedToPrevious,
    #[display("ALD")]
    PreviousCreditAdvice,
    #[display("ALE")]
    ReportingForm,
    #[display("ALF")]
    AuthorizationForExceptionTo,
    #[display("ALG")]
    DangerousGoodsSecurity,
    #[display("ALH")]
    DangerousGoodsTransportLicence,
    #[display("ALI")]
    PreviousRentalAgreement,
    #[display("ALJ")]
    NextRentalAgreementReason,
    #[display("ALK")]
    ConsigneeInvoice,
    #[display("ALL")]
    MessageBatch,
    #[display("ALM")]
    PreviousDeliverySchedule,
    #[display("ALN")]
    PhysicalInventoryRecount,
    #[display("ALO")]
    ReceivingAdvice,
    #[display("ALP")]
    ReturnableContainer,
    #[display("ALQ")]
    ReturnsNotice,
    #[display("ALR")]
    SalesForecast,
    #[display("ALS")]
    SalesReport,
    #[display("ALT")]
    PreviousTaxControl,
    #[display("ALU")]
    AerospaceGroundEquipment,
    #[display("ALV")]
    RegisteredCapital,
    #[display("ALW")]
    StandardOfInspection,
    #[display("ALX")]
    Model,
    #[display("ALY")]
    FinancialManagement,
    #[display("ALZ")]
    NotificationForCollection,
    #[display("AMA")]
    PreviousRequestForMetered,
    #[display("AMB")]
    NextRentalAgreement,
    #[display("AMC")]
    RequestForMeteredReading,
    #[display("AMD")]
    Hastening,
    #[display("AME")]
    RepairDataRequest,
    #[display("AMF")]
    ConsumptionDataRequest,
    #[display("AMG")]
    Profile,
    #[display("AMH")]
    Case,
    #[display("AMI")]
    GovernmentQualityAssuranceAnd,
    #[display("AMJ")]
    PaymentPlan,
    #[display("AMK")]
    ReplacedMeterUnit,
    #[display("AML")]
    ReplenishmentOrderRangeEnd,
    #[display("AMM")]
    InsurerAssigned,
    #[display("AMN")]
    CanadianExciseEntry,
    #[display("AMO")]
    PremiumRateTable,
    #[display("AMP")]
    AdviseThroughBank,
    #[display("AMQ")]
    UsDepartmentOfTransportation,
    #[display("AMR")]
    UsFoodAndDrugAdministration,
    #[display("AMS")]
    UsFederalCommunicationsCommission,
    #[display("AMT")]
    GoodsAndServicesTax,
    #[display("AMU")]
    IntegratedLogisticSupportCross,
    #[display("AMV")]
    Department,
    #[display("AMW")]
    BuyerCatalogue,
    #[display("AMX")]
    FinancialSettlementParty,
    #[display("AMY")]
    StandardVersion,
    #[display("AMZ")]
    Pipeline,
    #[display("ANA")]
    AccountServicingBank,
    #[display("ANB")]
    CompletedUnitsPaymentRequest,
    #[display("ANC")]
    PaymentInAdvanceRequest,
    #[display("AND")]
    ParentFile,
    #[display("ANE")]
    SubFile,
    #[display("ANF")]
    CadFileLayerConvention,
    #[display("ANG")]
    TechnicalRegulation,
    #[display("ANH")]
    PlotFile,
    #[display("ANI")]
    FileConversionJournal,
    #[display("ANJ")]
    Authorization,
    #[display("ANK")]
    AssignedByThirdParty,
    #[display("ANL")]
    Deposit,
    #[display("ANM")]
    NamedBank,
    #[display("ANN")]
    Drawee,
    #[display("ANO")]
    CaseOfNeedParty,
    #[display("ANP")]
    CollectingBank,
    #[display("ANQ")]
    RemittingBank,
    #[display("ANR")]
    PrincipalBank,
    #[display("ANS")]
    PresentingBank,
    #[display("ANT")]
    Consignee,
    #[display("ANU")]
    FinancialTransaction,
    #[display("ANV")]
    Credit,
    #[display("ANW")]
    ReceivingBankAuthorization,
    #[display("ANX")]
    Clearing,
    #[display("ANY")]
    SendingBank,
    #[display("AOA")]
    DocumentaryPayment,
    #[display("AOD")]
    AccountingFile,
    #[display("AOE")]
    SenderFile,
    #[display("AOF")]
    ReceiverFile,
    #[display("AOG")]
    SourceInternal,
    #[display("AOH")]
    PrincipalAOH,
    #[display("AOI")]
    Debit,
    #[display("AOJ")]
    Calendar,
    #[display("AOK")]
    WorkShift,
    #[display("AOL")]
    WorkBreakdownStructure,
    #[display("AOM")]
    OrganisationBreakdownStructure,
    #[display("AON")]
    WorkTaskCharge,
    #[display("AOO")]
    FunctionalWorkGroup,
    #[display("AOP")]
    WorkTeam,
    #[display("AOQ")]
    DepartmentAOQ,
    #[display("AOR")]
    StatementOfWork,
    #[display("AOS")]
    WorkPackage,
    #[display("AOT")]
    PlanningPackage,
    #[display("AOU")]
    CostAccount,
    #[display("AOV")]
    WorkOrder,
    #[display("AOW")]
    TransportationControl,
    #[display("AOX")]
    ConstraintNotation,
    #[display("AOY")]
    Eterms,
    #[display("AOZ")]
    ImplementationVersion,
    #[display("AP")]
    AccountsReceivable,
    #[display("APA")]
    IncorporatedLegal,
    #[display("APB")]
    PaymentInstalment,
    #[display("APC")]
    EquipmentOwner,
    #[display("APD")]
    CedentClaim,
    #[display("APE")]
    ReinsurerClaim,
    #[display("APF")]
    PriceSalesCatalogueResponse,
    #[display("APG")]
    GeneralPurposeMessage,
    #[display("APH")]
    InvoicingDataSheet,
    #[display("API")]
    InventoryReport,
    #[display("APJ")]
    CeilingFormula,
    #[display("APK")]
    PriceVariationFormula,
    #[display("APL")]
    AccountServicingBankMessage,
    #[display("APM")]
    PartySequence,
    #[display("APN")]
    PurchaserRequest,
    #[display("APO")]
    ContractorRequest,
    #[display("APP")]
    Accident,
    #[display("APQ")]
    CommercialAccountSummary,
    #[display("APR")]
    ContractBreakdown,
    #[display("APS")]
    ContractorRegistration,
    #[display("APT")]
    ApplicableCoefficient,
    #[display("APU")]
    SpecialBudgetAccount,
    #[display("APV")]
    AuthorisationForRepair,
    #[display("APW")]
    ManufacturerDefinedRepairRates,
    #[display("APX")]
    OriginalSubmitterLog,
    #[display("APY")]
    OriginalSubmitterParentData,
    #[display("APZ")]
    OriginalSubmitterChildData,
    #[display("AQA")]
    EntryPointAssessmentLog,
    #[display("AQB")]
    EntryPointAssessmentLogParent,
    #[display("AQC")]
    EntryPointAssessmentLogChild,
    #[display("AQD")]
    DataStructureTag,
    #[display("AQE")]
    CentralSecretariatLog,
    #[display("AQF")]
    CentralSecretariatLogParent,
    #[display("AQG")]
    CentralSecretariatLogChild,
    #[display("AQH")]
    InternationalAssessmentLog,
    #[display("AQI")]
    InternationalAssessmentLogParent,
    #[display("AQJ")]
    InternationalAssessmentLogChild,
    #[display("AQK")]
    StatusReport,
    #[display("AQL")]
    MessageDesignGroup,
    #[display("AQM")]
    UsCustomsService,
    #[display("AQN")]
    BeginningJobSequence,
    #[display("AQO")]
    SenderClause,
    #[display("AQP")]
    DunAndBradstreetCanada,
    #[display("AQQ")]
    FrenchApe,
    #[display("AQR")]
    DunAndBradstreet,
    #[display("AQS")]
    EuNace,
    #[display("AQT")]
    FrenchNaf,
    #[display("AQU")]
    RegisteredContractorActivityType,
    #[display("AQV")]
    GermanFederalStatistics,
    #[display("AQW")]
    StateOrProvinceAssigned,
    #[display("AQX")]
    InstituteOfSecurityAnd,
    #[display("AQY")]
    File,
    #[display("AQZ")]
    BankruptcyProcedure,
    #[display("ARA")]
    NationalGovernmentBusiness,
    #[display("ARB")]
    PriorDataUniversalSystem,
    #[display("ARC")]
    CompaniesRegistryOffice,
    #[display("ARD")]
    CostaRicanJudicial,
    #[display("ARE")]
    ColombianNit,
    #[display("ARF")]
    Patron,
    #[display("ARG")]
    VenezuelanRif,
    #[display("ARH")]
    Ruc,
    #[display("ARI")]
    TokyoShokoResearch,
    #[display("ARJ")]
    PersonalIdentityCard,
    #[display("ARK")]
    FrenchSirene,
    #[display("ARL")]
    FrenchSiret,
    #[display("ARM")]
    PublicationIssue,
    #[display("ARN")]
    OriginalFiling,
    #[display("ARO")]
    DocumentPage,
    #[display("ARP")]
    PublicFilingRegistration,
    #[display("ARQ")]
    MexicanRfc,
    #[display("ARR")]
    SocialSecurity,
    #[display("ARS")]
    DocumentVolume,
    #[display("ART")]
    Book,
    #[display("ARU")]
    StockExchangeCompany,
    #[display("ARV")]
    ImputationAccount,
    #[display("ARW")]
    FinancialPhase,
    #[display("ARX")]
    TechnicalPhase,
    #[display("ARY")]
    PriorContractorRegistration,
    #[display("ARZ")]
    StockAdjustment,
    #[display("ASA")]
    Dispensation,
    #[display("ASB")]
    Investment,
    #[display("ASC")]
    AssumingCompany,
    #[display("ASD")]
    BudgetChapter,
    #[display("ASE")]
    DutyFreeProductsSecurity,
    #[display("ASF")]
    DutyFreeProductsReceipt,
    #[display("ASG")]
    PartyInformationMessage,
    #[display("ASH")]
    FormalStatement,
    #[display("ASI")]
    ProofOfDelivery,
    #[display("ASJ")]
    SupplierCreditClaim,
    #[display("ASK")]
    PictureOfActualProduct,
    #[display("ASL")]
    PictureOfGenericProduct,
    #[display("ASM")]
    TradingPartner,
    #[display("ASN")]
    PriorTradingPartner,
    #[display("ASO")]
    Password,
    #[display("ASP")]
    FormalReport,
    #[display("ASQ")]
    FundAccount,
    #[display("ASR")]
    SafeCustody,
    #[display("ASS")]
    MasterAccount,
    #[display("AST")]
    Group,
    #[display("ASU")]
    AccountingTransmission,
    #[display("ASV")]
    ProductDataFile,
    #[display("ASW")]
    CadastroGeralDoContribuinte,
    #[display("ASX")]
    ForeignResident,
    #[display("ASY")]
    CdRom,
    #[display("ASZ")]
    PhysicalMedium,
    #[display("ATA")]
    FinancialCancellation,
    #[display("ATB")]
    PurchaseForExportCustoms,
    #[display("ATC")]
    Judgment,
    #[display("ATD")]
    Secretariat,
    #[display("ATE")]
    PreviousBankingStatusMessage,
    #[display("ATF")]
    LastReceivedBankingStatus,
    #[display("ATG")]
    BankDocumentaryProcedure,
    #[display("ATH")]
    CustomerDocumentaryProcedure,
    #[display("ATI")]
    SafeDepositBox,
    #[display("ATJ")]
    ReceivingBankgiro,
    #[display("ATK")]
    SendingBankgiro,
    #[display("ATL")]
    Bankgiro,
    #[display("ATM")]
    Guarantee,
    #[display("ATN")]
    CollectionInstrument,
    #[display("ATO")]
    ConvertedPostgiro,
    #[display("ATP")]
    CostCentreAlignment,
    #[display("ATQ")]
    DutchKvk,
    #[display("ATR")]
    InstitutBelgoLuxembourgeoisDe,
    #[display("ATS")]
    ExternalObject,
    #[display("ATT")]
    ExceptionalTransportAuthorisation,
    #[display("ATU")]
    ClaveUnicaDeIdentificacion,
    #[display("ATV")]
    Rut,
    #[display("ATW")]
    FlatRackContainerBundle,
    #[display("ATX")]
    TransportEquipmentAcceptanceOrder,
    #[display("ATY")]
    TransportEquipmentReleaseOrder,
    #[display("ATZ")]
    ShipStay,
    #[display("AU")]
    AuthorizationToMeetCompetition,
    #[display("AUA")]
    PlaceOfPositioning,
    #[display("AUB")]
    Party,
    #[display("AUC")]
    IssuedPrescription,
    #[display("AUD")]
    Collection,
    #[display("AUE")]
    TravelService,
    #[display("AUF")]
    ConsignmentStockContract,
    #[display("AUG")]
    ImporterLetterOfCredit,
    #[display("AUH")]
    PerformedPrescription,
    #[display("AUI")]
    Image,
    #[display("AUJ")]
    ProposedPurchaseOrder,
    #[display("AUK")]
    ApplicationForFinancialSupport,
    #[display("AUL")]
    ManufacturingQualityAgreement,
    #[display("AUM")]
    SoftwareEditor,
    #[display("AUN")]
    Software,
    #[display("AUO")]
    SoftwareQuality,
    #[display("AUP")]
    ConsolidatedOrders,
    #[display("AUQ")]
    CustomsBindingRuling,
    #[display("AUR")]
    CustomsNonBindingRuling,
    #[display("AUS")]
    DeliveryRoute,
    #[display("AUT")]
    NetAreaSupplier,
    #[display("AUU")]
    TimeSeries,
    #[display("AUV")]
    ConnectingPointToCentral,
    #[display("AUW")]
    MarketingPlan,
    #[display("AUX")]
    EntityPrevious,
    #[display("AUY")]
    Isic,
    #[display("AUZ")]
    CustomsPreApprovalRuling,
    #[display("AV")]
    AccountPayable,
    #[display("AVA")]
    FirstFinancialInstitutionTransaction,
    #[display("AVB")]
    ProductCharacteristicsDirectory,
    #[display("AVC")]
    SupplierCustomer,
    #[display("AVD")]
    InventoryReportRequest,
    #[display("AVE")]
    MeteringPoint,
    #[display("AVF")]
    PassengerReservation,
    #[display("AVG")]
    SlaughterhouseApproval,
    #[display("AVH")]
    MeatCuttingPlantApproval,
    #[display("AVI")]
    CustomerTravelService,
    #[display("AVJ")]
    ExportControlClassification,
    #[display("AVK")]
    BrokerAVK,
    #[display("AVL")]
    ConsignmentInformation,
    #[display("AVM")]
    GoodsItemInformation,
    #[display("AVN")]
    DangerousGoodsInformation,
    #[display("AVO")]
    PilotageServicesExemption,
    #[display("AVP")]
    PersonRegistration,
    #[display("AVQ")]
    PlaceOfPackingApproval,
    #[display("AVR")]
    OriginalMandate,
    #[display("AVS")]
    Mandate,
    #[display("AVT")]
    ReservationStationIndentifier,
    #[display("AVU")]
    UniqueGoodsShipment,
    #[display("AVV")]
    FrameworkAgreement,
    #[display("AVW")]
    HashValue,
    #[display("AVX")]
    Movement,
    #[display("AVY")]
    EconomicOperatorsRegistrationAnd,
    #[display("AVZ")]
    Local,
    #[display("AWA")]
    Rate,
    #[display("AWB")]
    AirWaybill,
    #[display("AWC")]
    DocumentaryCreditAmendment,
    #[display("AWD")]
    AdvisingBank,
    #[display("AWE")]
    CostCentre,
    #[display("AWF")]
    WorkItemQuantityDetermination,
    #[display("AWG")]
    InternalDataProcess,
    #[display("AWH")]
    CategoryOfWork,
    #[display("AWI")]
    PolicyForm,
    #[display("AWJ")]
    NetArea,
    #[display("AWK")]
    ServiceProvider,
    #[display("AWL")]
    ErrorPosition,
    #[display("AWM")]
    ServiceCategory,
    #[display("AWN")]
    ConnectedLocation,
    #[display("AWO")]
    RelatedParty,
    #[display("AWP")]
    LatestAccountingEntryRecord,
    #[display("AWQ")]
    AccountingEntry,
    #[display("AWR")]
    DocumentOriginal,
    #[display("AWS")]
    HygienicCertificateNational,
    #[display("AWT")]
    Administrative,
    #[display("AWU")]
    PickUpSheet,
    #[display("AWV")]
    Phone,
    #[display("AWW")]
    BuyerFund,
    #[display("AWX")]
    CompanyTradingAccount,
    #[display("AWY")]
    ReservedGoods,
    #[display("AWZ")]
    HandlingAndMovement,
    #[display("AXA")]
    InstructionToDespatch,
    #[display("AXB")]
    InstructionForReturns,
    #[display("AXC")]
    MeteredServicesConsumptionReport,
    #[display("AXD")]
    OrderStatusEnquiry,
    #[display("AXE")]
    FirmBooking,
    #[display("AXF")]
    ProductInquiry,
    #[display("AXG")]
    SplitDelivery,
    #[display("AXH")]
    ServiceRelation,
    #[display("AXI")]
    SerialShippingContainer,
    #[display("AXJ")]
    TestSpecification,
    #[display("AXK")]
    TransportStatusReport,
    #[display("AXL")]
    ToolingContract,
    #[display("AXM")]
    Formula,
    #[display("AXN")]
    PreAgreement,
    #[display("AXO")]
    ProductCertification,
    #[display("AXP")]
    ConsignmentContract,
    #[display("AXQ")]
    ProductSpecification,
    #[display("AXR")]
    PayrollDeductionAdvice,
    #[display("AXS")]
    EuTraces,
    #[display("AXU")]
    Axu,
    #[display("BA")]
    BeginningMeterReadingActual,
    #[display("BC")]
    BuyerContract,
    #[display("BD")]
    Bid,
    #[display("BE")]
    BeginningMeterReadingEstimated,
    #[display("BH")]
    HouseBillOfLading,
    #[display("BM")]
    BillOfLading,
    #[display("BN")]
    ConsignmentCarrierAssigned,
    #[display("BO")]
    BlanketOrder,
    #[display("BR")]
    BrokerOrSalesOffice,
    #[display("BT")]
    BatchLot,
    #[display("BTP")]
    BatteryAndAccumulatorProducer,
    #[display("BW")]
    BlendedWith,
    #[display("CAS")]
    IataCargoAgentCass,
    #[display("CAT")]
    MatchingOfEntriesBalanced,
    #[display("CAU")]
    EntryFlagging,
    #[display("CAV")]
    MatchingOfEntriesUnbalanced,
    #[display("CAW")]
    DocumentInternal,
    #[display("CAX")]
    EuropeanValueAddedTax,
    #[display("CAY")]
    CostAccounting,
    #[display("CAZ")]
    GridOperatorCustomer,
    #[display("CBA")]
    TicketControl,
    #[display("CBB")]
    OrderShipmentGrouping,
    #[display("CD")]
    CreditNote,
    #[display("CEC")]
    CedingCompany,
    #[display("CED")]
    DebitLetter,
    #[display("CFE")]
    ConsigneeFurtherOrder,
    #[display("CFF")]
    AnimalFarmLicence,
    #[display("CFO")]
    ConsignorFurtherOrder,
    #[display("CG")]
    ConsigneeOrder,
    #[display("CH")]
    CustomerCatalogue,
    #[display("CK")]
    Cheque,
    #[display("CKN")]
    Checking,
    #[display("CM")]
    CreditMemo,
    #[display("CMR")]
    RoadConsignmentNote,
    #[display("CN")]
    Carrier,
    #[display("CNO")]
    ChargesNoteAttachmentIndicator,
    #[display("COF")]
    CallOffOrder,
    #[display("CP")]
    ConditionOfPurchase,
    #[display("CR")]
    Customer,
    #[display("CRN")]
    TransportMeansJourney,
    #[display("CS")]
    ConditionOfSale,
    #[display("CST")]
    TeamAssignment,
    #[display("CT")]
    Contract,
    #[display("CU")]
    ConsignmentConsignorAssigned,
    #[display("CV")]
    ContainerOperators,
    #[display("CW")]
    Package,
    #[display("CZ")]
    CooperationContract,
    #[display("DA")]
    DefermentApproval,
    #[display("DAN")]
    DebitAccount,
    #[display("DB")]
    BuyerDebtor,
    #[display("DI")]
    DistributorInvoice,
    #[display("DL")]
    DebitNote,
    #[display("DM")]
    Document,
    #[display("DQ")]
    DeliveryNote,
    #[display("DR")]
    DockReceipt,
    #[display("EA")]
    EndingMeterReadingActual,
    #[display("EB")]
    EmbargoPermit,
    #[display("ED")]
    ExportDeclaration,
    #[display("EE")]
    EndingMeterReadingEstimated,
    #[display("EEP")]
    ElectricalAndElectronicEquipment,
    #[display("EI")]
    Employer,
    #[display("EN")]
    Embargo,
    #[display("EQ")]
    Equipment,
    #[display("ER")]
    ContainerEquipmentReceipt,
    #[display("ERN")]
    Exporter,
    #[display("ET")]
    ExcessTransportation,
    #[display("EX")]
    ExportPermit,
    #[display("FC")]
    Fiscal,
    #[display("FF")]
    ConsignmentFreightForwarderAssigned,
    #[display("FI")]
    FileLine,
    #[display("FLW")]
    Flow,
    #[display("FN")]
    FreightBill,
    #[display("FO")]
    ForeignExchange,
    #[display("FS")]
    FinalSequence,
    #[display("FT")]
    FreeZone,
    #[display("FV")]
    FileVersion,
    #[display("FX")]
    ForeignExchangeContract,
    #[display("GA")]
    Standard,
    #[display("GC")]
    GovernmentContract,
    #[display("GD")]
    StandardGD,
    #[display("GDN")]
    GeneralDeclaration,
    #[display("GN")]
    Government,
    #[display("HS")]
    HarmonisedSystem,
    #[display("HWB")]
    HouseWaybill,
    #[display("IA")]
    InternalVendor,
    #[display("IB")]
    Bond,
    #[display("ICA")]
    IataCargoAgent,
    #[display("ICE")]
    InsuranceCertificate,
    #[display("ICO")]
    InsuranceContract,
    #[display("II")]
    InitialSampleInspectionReport,
    #[display("IL")]
    InternalOrder,
    #[display("INB")]
    IntermediaryBroker,
    #[display("INN")]
    InterchangeNew,
    #[display("INO")]
    InterchangeOld,
    #[display("IP")]
    ImportPermit,
    #[display("IS")]
    InvoiceSuffix,
    #[display("IT")]
    InternalCustomer,
    #[display("IV")]
    Invoice,
    #[display("JB")]
    Job,
    #[display("JE")]
    EndingJobSequence,
    #[display("LA")]
    ShippingLabelSerial,
    #[display("LAN")]
    LoadingAuthorisation,
    #[display("LAR")]
    LowerInRange,
    #[display("LB")]
    Lockbox,
    #[display("LC")]
    LetterOfCredit,
    #[display("LI")]
    DocumentLine,
    #[display("LO")]
    LoadPlanning,
    #[display("LRC")]
    ReservationOffice,
    #[display("LS")]
    BarCodedLabelSerial,
    #[display("MA")]
    ShipNoticeManifest,
    #[display("MB")]
    MasterBillOfLading,
    #[display("MF")]
    ManufacturerPart,
    #[display("MG")]
    MeterUnit,
    #[display("MH")]
    ManufacturingOrder,
    #[display("MR")]
    MessageRecipient,
    #[display("MRN")]
    Mailing,
    #[display("MS")]
    MessageSender,
    #[display("MSS")]
    ManufacturerMaterialSafetyData,
    #[display("MWB")]
    MasterAirWaybill,
    #[display("NA")]
    NorthAmericanHazardousGoods,
    #[display("NF")]
    NotaFiscal,
    #[display("OH")]
    CurrentInvoice,
    #[display("OI")]
    PreviousInvoice,
    #[display("ON")]
    OrderBuyerAssigned,
    #[display("OP")]
    OriginalPurchaseOrder,
    #[display("OR")]
    GeneralOrder,
    #[display("PB")]
    PayerFinancialInstitutionAccount,
    #[display("PC")]
    Production,
    #[display("PD")]
    PromotionDeal,
    #[display("PE")]
    Plant,
    #[display("PF")]
    PrimeContractorContract,
    #[display("PI")]
    PriceListVersion,
    #[display("PK")]
    PackingList,
    #[display("PL")]
    PriceList,
    #[display("POR")]
    PurchaseOrderResponse,
    #[display("PP")]
    PurchaseOrderChange,
    #[display("PQ")]
    Payment,
    #[display("PR")]
    PriceQuote,
    #[display("PS")]
    PurchaseOrderSuffix,
    #[display("PW")]
    PriorPurchaseOrder,
    #[display("PY")]
    PayeeFinancialInstitutionAccount,
    #[display("RA")]
    RemittanceAdvice,
    #[display("RC")]
    RailRoadRouting,
    #[display("RCN")]
    RailwayConsignmentNote,
    #[display("RE")]
    Release,
    #[display("REN")]
    ConsignmentReceipt,
    #[display("RF")]
    Export,
    #[display("RR")]
    PayerBankTransitRouting,
    #[display("RT")]
    PayeeBankTransitRouting,
    #[display("SA")]
    SalesPerson,
    #[display("SB")]
    SalesRegion,
    #[display("SD")]
    SalesDepartment,
    #[display("SE")]
    Serial,
    #[display("SEA")]
    AllocatedSeat,
    #[display("SF")]
    ShipFrom,
    #[display("SH")]
    PreviousHighestSchedule,
    #[display("SI")]
    ShipperShipmentId,
    #[display("SM")]
    SalesOffice,
    #[display("SN")]
    TransportEquipmentSeal,
    #[display("SP")]
    ScanLine,
    #[display("SQ")]
    EquipmentSequence,
    #[display("SRN")]
    Shipment,
    #[display("SS")]
    Sellers,
    #[display("STA")]
    Station,
    #[display("SW")]
    SwapOrder,
    #[display("SZ")]
    Specification,
    #[display("TB")]
    TruckerBillOfLading,
    #[display("TCR")]
    TerminalOperatorConsignment,
    #[display("TE")]
    TelexMessage,
    #[display("TF")]
    Transfer,
    #[display("TI")]
    TIRCarnet,
    #[display("TIN")]
    TransportInstruction,
    #[display("TL")]
    TaxExemptionLicence,
    #[display("TN")]
    Transaction,
    #[display("TP")]
    TestReport,
    #[display("UAR")]
    UpperOfRange,
    #[display("UC")]
    UltimateCustomer,
    #[display("UCN")]
    UniqueConsignment,
    #[display("UN")]
    UnitedNationsDangerousGoods,
    #[display("UO")]
    UltimateCustomerOrder,
    #[display("URI")]
    UniformResource,
    #[display("VA")]
    VATRegistration,
    #[display("VC")]
    VendorContract,
    #[display("VGR")]
    TransportEquipmentGrossMass,
    #[display("VM")]
    Vessel,
    #[display("VN")]
    Order,
    #[display("VON")]
    Voyage,
    #[display("VOR")]
    GrossMassVerification,
    #[display("VP")]
    VendorProduct,
    #[display("VR")]
    VendorID,
    #[display("VS")]
    VendorOrderSuffix,
    #[display("VT")]
    MotorVehicle,
    #[display("VV")]
    Voucher,
    #[display("WE")]
    WarehouseEntry,
    #[display("WM")]
    WeightAgreement,
    #[display("WN")]
    Well,
    #[display("WR")]
    WarehouseReceipt,
    #[display("WS")]
    WarehouseStorageLocation,
    #[display("WY")]
    RailWaybill,
    #[display("XA")]
    CompanyPlaceRegistration,
    #[display("XC")]
    CargoControl,
    #[display("XP")]
    PreviousCargoControl,
    #[display("ZZZ")]
    MutuallyDefined,
}

impl TryFrom<&str> for InvoicedObjectType {
    type Error = Error;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        <Self as FromStr>::from_str(value).map_err(Into::into)
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn parses_a_known_code() {
        let scheme: InvoicedObjectType =
            "AAA".parse().expect("AAA is a valid invoiced object type");
        assert_eq!(scheme.to_string(), "AAA");
    }

    #[test]
    fn rejects_an_unknown_code() {
        assert!("ZZZZ".parse::<InvoicedObjectType>().is_err());
    }
}
