//! The item classification scheme code of a line item (`BT-158`, UNTDID 7143).
//!
//! Sources:
//! * [EN-16931 codelist](https://github.com/ConnectingEurope/eInvoicing-EN16931/blob/master/ubl/schematron/codelist/EN16931-UBL-codes.sch), rule `BR-CL-13`.
//! * Variant names follow the names and descriptions of [UNCL7143](https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL7143/).

use crate::Error;
use crate::prelude::*;

/// The item classification scheme (`BT-158`, UNTDID 7143): the external scheme that a
/// line item classification identifier belongs to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Display, FromStr)]
pub enum ItemClassification {
    #[display("AA")]
    ProductVersionNumber,
    #[display("AB")]
    Assembly,
    #[display("AC")]
    HealthIndustryBarcode,
    #[display("AD")]
    ColdRollNumber,
    #[display("AE")]
    HotRollNumber,
    #[display("AF")]
    SlabNumber,
    #[display("AG")]
    SoftwareRevisionNumber,
    #[display("AH")]
    UpcConsumerPackage155Format,
    #[display("AI")]
    UpcConsumerPackage1551Format,
    #[display("AJ")]
    SampleNumber,
    #[display("AK")]
    PackNumber,
    #[display("AL")]
    UpcShippingContainerShortCode,
    #[display("AM")]
    UpcShippingContainerLongCode,
    #[display("AN")]
    UpcSuffix,
    #[display("AO")]
    StateLabelCode,
    #[display("AP")]
    HeatNumber,
    #[display("AQ")]
    CouponNumber,
    #[display("AR")]
    ResourceNumber,
    #[display("AS")]
    WorkTaskNumber,
    #[display("AT")]
    PriceLookUpNumber,
    #[display("AU")]
    NatoStockNumber,
    #[display("AV")]
    RefinedProductCode,
    #[display("AW")]
    Exhibit,
    #[display("AX")]
    EndItem,
    #[display("AY")]
    UsFederalSupplyCode,
    #[display("AZ")]
    EngineeringDataList,
    #[display("BA")]
    MilestoneEventNumber,
    #[display("BB")]
    LotNumber,
    #[display("BC")]
    UsNationalDrugCode442Format,
    #[display("BD")]
    UsNationalDrugCode532Format,
    #[display("BE")]
    UsNationalDrugCode541Format,
    #[display("BF")]
    UsNationalDrugCode542Format,
    #[display("BG")]
    UsNationalDrugCode,
    #[display("BH")]
    PartNumber,
    #[display("BI")]
    LocalStockNumber,
    #[display("BJ")]
    NextHigherAssemblyNumber,
    #[display("BK")]
    DataCategory,
    #[display("BL")]
    ControlNumber,
    #[display("BM")]
    SpecialMaterialCode,
    #[display("BN")]
    LocallyAssignedControlNumber,
    #[display("BO")]
    BuyerColour,
    #[display("BP")]
    BuyerPartNumber,
    #[display("BQ")]
    VariableMeasureProductCode,
    #[display("BR")]
    FinancialPhase,
    #[display("BS")]
    ContractBreakdown,
    #[display("BT")]
    TechnicalPhase,
    #[display("BU")]
    DyeLotNumber,
    #[display("BV")]
    DailyActivityStatement,
    #[display("BW")]
    PeriodicalActivityStatement,
    #[display("BX")]
    WeeklyActivityStatement,
    #[display("BY")]
    MonthlyActivityStatement,
    #[display("BZ")]
    OriginalEquipmentNumber,
    #[display("CC")]
    IndustryCommodityCode,
    #[display("CG")]
    CommodityGrouping,
    #[display("CL")]
    ColourNumber,
    #[display("CR")]
    ContractNumber,
    #[display("CV")]
    CustomsArticleNumber,
    #[display("DR")]
    DrawingRevisionNumber,
    #[display("DW")]
    Drawing,
    #[display("EC")]
    EngineeringChangeLevel,
    #[display("EF")]
    MaterialCode,
    #[display("EMD")]
    EuMedicalDeviceNomenclature,
    #[display("EN")]
    InternationalArticleNumber,
    #[display("FS")]
    FishSpecies,
    #[display("GB")]
    BuyerProductGroupCode,
    #[display("GN")]
    NationalProductGroupCode,
    #[display("GMN")]
    GlobalModelNumber,
    #[display("GS")]
    GeneralSpecificationNumber,
    #[display("HS")]
    HarmonisedSystem,
    #[display("IB")]
    ISBN,
    #[display("IN")]
    BuyerItemNumber,
    #[display("IS")]
    ISSN,
    #[display("IT")]
    BuyerStyleNumber,
    #[display("IZ")]
    BuyerSizeCode,
    #[display("MA")]
    MachineNumber,
    #[display("MF")]
    ManufacturerArticleNumber,
    #[display("MN")]
    ModelNumber,
    #[display("MP")]
    ProductServiceNumber,
    #[display("NB")]
    BatchNumber,
    #[display("ON")]
    CustomerOrderNumber,
    #[display("PD")]
    PartNumberDescription,
    #[display("PL")]
    PurchaserOrderLineNumber,
    #[display("PO")]
    PurchaseOrderNumber,
    #[display("PPI")]
    PhytosanitaryPassport,
    #[display("PV")]
    PromotionalVariantNumber,
    #[display("QS")]
    BuyerSizeQualifier,
    #[display("RC")]
    ReturnableContainerNumber,
    #[display("RN")]
    ReleaseNumber,
    #[display("RU")]
    RunNumber,
    #[display("RY")]
    ModelYear,
    #[display("SA")]
    SupplierArticleNumber,
    #[display("SG")]
    StandardProductGroup,
    #[display("SK")]
    StockKeepingUnit,
    #[display("SN")]
    SerialNumber,
    #[display("SRS")]
    SwedishPlumbingAndHeatingNumber,
    #[display("SRT")]
    FrenchProductCode5Digit,
    #[display("SRU")]
    FrenchProductCode9Digit,
    #[display("SRV")]
    GlobalTradeItemNumber,
    #[display("SRW")]
    EuMeterDataSystem,
    #[display("SRX")]
    SlaughterNumber,
    #[display("SRY")]
    OfficialAnimalNumber,
    #[display("SRZ")]
    HarmonizedTariffSchedule,
    #[display("SS")]
    SupplierSupplierArticleNumber,
    #[display("SSA")]
    UsDotHazardousGoodsCode,
    #[display("SSB")]
    UsAirlineTariff,
    #[display("SSC")]
    UsCustomsAndBorderProtectionCode,
    #[display("SSD")]
    UsCivilAviationCode,
    #[display("SSE")]
    UsHazardousMaterialsDotCode,
    #[display("SSF")]
    UsEndorsement,
    #[display("SSG")]
    UsAirForceRegulation,
    #[display("SSH")]
    Breed,
    #[display("SSI")]
    ChemicalAbstractServiceNumber,
    #[display("SSJ")]
    EngineModelDesignation,
    #[display("SSK")]
    UsInstitutionalMeatSpecification,
    #[display("SSL")]
    PriceLookUpCode,
    #[display("SSM")]
    MaritimeOrganizationCode,
    #[display("SSN")]
    UsBureauOfExplosivesHazardousGoodsCode,
    #[display("SSO")]
    UnDangerousGoodsCode,
    #[display("SSP")]
    BotanicalNomenclatureCode,
    #[display("SSQ")]
    ZoologicalNomenclatureCode,
    #[display("SSR")]
    CultivatedPlantsNomenclatureCode,
    #[display("SSS")]
    DistributorArticleIdentifier,
    #[display("SST")]
    NorwegianMarketCode,
    #[display("SSU")]
    SupplierAssignedCode,
    #[display("SSV")]
    MexicanMarketCode,
    #[display("SSW")]
    GermanMarketCode,
    #[display("SSX")]
    FinnishMarketCode,
    #[display("SSY")]
    CanadianMarketCode,
    #[display("SSZ")]
    FrenchMarketCode,
    #[display("ST")]
    StyleNumber,
    #[display("STA")]
    DutchMarketCode,
    #[display("STB")]
    JapaneseMarketCode,
    #[display("STC")]
    EuDairySubsidyCode,
    #[display("STD")]
    SpanishMarketCode,
    #[display("STE")]
    PolishMarketCode,
    #[display("STF")]
    RussianStandardizationBody,
    #[display("STG")]
    AustrianMarketCode,
    #[display("STH")]
    ItalianMarketCode,
    #[display("STI")]
    EuCommonProcurementVocabulary,
    #[display("STJ")]
    FoodserviceDistributorsAssociation,
    #[display("STK")]
    AmericanHospitalFormularyService,
    #[display("STL")]
    AnatomicalTherapeuticChemical,
    #[display("STM")]
    FrenchMedicalDeviceCode,
    #[display("STN")]
    CanadianMedicalDeviceCode,
    #[display("STO")]
    ItalianMedicalDeviceCode,
    #[display("STP")]
    UkMedicinesAndDeviceCode,
    #[display("STQ")]
    MaterialServiceCode,
    #[display("STR")]
    EuInVitroDiagnosticsCode,
    #[display("STS")]
    EuGenericArticleRegister,
    #[display("STT")]
    GlobalMedicalDevicesNomenclature,
    #[display("STU")]
    GenericProductIdentifier,
    #[display("STV")]
    UsHealthcareProcedureCodingSystem,
    #[display("STW")]
    PatientSafetyCode,
    #[display("STX")]
    MedicalRegulatoryDictionary,
    #[display("STY")]
    GermanMedicalCode,
    #[display("STZ")]
    NorthAmericanMarketCode,
    #[display("SUA")]
    UkProductServiceCode,
    #[display("SUB")]
    UsFdaProductCode,
    #[display("SUC")]
    SystematizedMedicineNomenclature,
    #[display("SUD")]
    UniversalMedicalDeviceNomenclature,
    #[display("SUE")]
    ReturnableAssetIdentifier,
    #[display("SUF")]
    MobileEquipmentIdentity,
    #[display("SUG")]
    EuMaritimeSafetyWasteCode,
    #[display("SUH")]
    ShipStoreCode,
    #[display("SUI")]
    EmergencyFireCode,
    #[display("SUJ")]
    EmergencySpillageCode,
    #[display("SUK")]
    DangerousGoodsPackingGroup,
    #[display("SUL")]
    BulkChemicalCode,
    #[display("SUM")]
    DangerousGoodsSubsidiaryRiskClass,
    #[display("TG")]
    TransportGroupNumber,
    #[display("TSN")]
    TaxonomicSerialNumber,
    #[display("TSO")]
    DangerousGoodsMainHazardClass,
    #[display("TSP")]
    EuCombinedNomenclature,
    #[display("TSQ")]
    TherapeuticCode,
    #[display("TSR")]
    EuWasteCatalogue,
    #[display("TSS")]
    PriceGroupingCode,
    #[display("TST")]
    UnspscCommodityCode,
    #[display("TSU")]
    EuHazardousSubstanceCode,
    #[display("UA")]
    UltimateCustomerArticleNumber,
    #[display("UP")]
    UniversalProductCode,
    #[display("VN")]
    VendorItemNumber,
    #[display("VP")]
    VendorPartNumber,
    #[display("VS")]
    VendorSupplementalItemNumber,
    #[display("VX")]
    VendorSpecificationNumber,
    #[display("ZZZ")]
    MutuallyDefined,
}

impl TryFrom<&str> for ItemClassification {
    type Error = Error;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        <Self as FromStr>::from_str(value).map_err(Into::into)
    }
}

#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn parses_a_known_code() {
        let scheme: ItemClassification = "HS".parse().expect("HS is a valid item classification");

        assert_eq!(scheme, ItemClassification::HarmonisedSystem);
        assert_eq!(scheme.to_string(), "HS");
    }

    #[test]
    fn rejects_an_unknown_code() {
        assert!("XX".parse::<ItemClassification>().is_err());
    }

    #[test]
    fn converts_via_try_from() {
        assert_eq!(
            ItemClassification::try_from("SRV").expect("SRV is a valid item classification"),
            ItemClassification::GlobalTradeItemNumber
        );
        assert!(matches!(
            ItemClassification::try_from("XX"),
            Err(Error::InvalidValue { .. })
        ));
    }
}
